### ISSUE TITLE
It does not work with PAP protocal and password length is more than 16.  

### ISSUE THREAD

**Issue by BruceZu** [ctran/TinyRadius#15]
found 2 related feedback. and one pull request here.
https://sourceforge.net/p/tinyradius/discussion/461293/thread/14f97cb6/
https://sourceforge.net/p/tinyradius/discussion/461293/thread/dcedb4ed/
Just want to know any plan to fix it? 
Thank you!

**Comment by ctran** [comment]
I don't have a need to use this library anymore.  If you want to submit a PR for it, I'll be happy to review and merge it.

**Comment by BruceZu** [comment]
@ctran  Thank you for your feedback. 
It is just a small bug fix and the PR is ready for review.  While our end user wants it much.
By far we have 2 MRs.  It is okay to me you select anyone to merge. 
Thank you for your time!

**Comment by ctran** [comment]
This is fixed with #16.

**Comment by agimbel** [comment]
When will be a new release with this fix available to download ?

**Comment by ctran** [comment]
It's there now:
> https://bintray.com/ctran/maven/tinyradius/1.1.0
