### ISSUE TITLE
Distribution not available on any public repo

### ISSUE THREAD

**Issue by kkishordn** [ctran/TinyRadius#4]
Do you plan to make its dist available on any public maven repos, like central/jcenter/bintray etc? i found one on SourceForge here (https://sourceforge.net/projects/tinyradius/files/) but that seems to be quite old - last updated in 2010, while your github repo is updated just 21 days ago!

**Comment by ctran** [comment]
I wasn't aware of anyone would be interested in getting this from a public repo.  If that helps you, I can try to do that.

**Comment by kkishordn** [comment]
That would help a lot :) thanks for this awesome work and a quick response to my question.

**Comment by tomaskir** [comment]
I would also really appreciate having this available in a public Maven repo.

**Comment by JacksonBailey** [comment]
One of my company's services uses this. I had to migrate that service from an old SVN repo to a new Git repo so I built it to make sure it all compiled but there a was missing this jar file! Luckily Google brought me here. We are using the 1.0.2 version (at `7ea6c472f96530e99e74d9d58820d91ce80c278e`). The code is old, from 2014, and it uses version 1.0.2, so I know that commit is the one we are using a jar of (that commit is the only one in 2014 with version 1.0.2).

Actually it would be helpful if that commit was tagged `v1.0.2` so people know that was the "release". Or once you get it deployed to jcenter/central if there aren't any "real" changes then tag that one as `v1.0.2`.

I know if we are using it, others may be too. :smile:

**Comment by ctran** [comment]
Could you create a new issue for that and I'll do that tonight?

**Comment by goonsunday** [comment]
much appreciate about this project and it's very useful. I am using it mporting maven repo: https://mvnrepository.com/artifact/com.hynnet/tinyradius (I know this repo is not created by you) but it's  quite old. Looking forward updated maven repo.

**Comment by CaiCookie** [comment]
Hello，Can I ask you some question ?I am using you project to do some develpment by myself,I tested the code it can send the message from client to server but the client can't get the response ,Shold I some set some other configuration at the client?

**Comment by JacksonBailey** [comment]
@CaiCookie this isn't really a forum for chatting, this is an issue board. This issue is "Distribution not available on any public repo". Your problem doesn't seem to be related to that. You should open another issue and ask for assistance there instead so as to not bother everyone subscribed to this issue.  :smile:

**Comment by Nivani** [comment]
For people currently looking for a way, version 1.0.2 is available here: https://bintray.com/ctran/maven/tinyradius

@ctran is it ok to use this repo?

To use this in your build you need to add ctran's bintray repository:
- In a **Gradle** build you can add the repository like this:
```
repositories {
...
    maven { url 'https://dl.bintray.com/ctran/maven' }
...
}
```
- In a **Maven** build it would be something like this:
```
<repositories>
...
  <repository>
    <id>ctran-repo</id>
    <name>ctran repo</name>
    <url>https://dl.bintray.com/ctran/maven</url>
  </repository>
...
</repositories>
```

**Comment by ctran** [comment]
Yes.  All release builds are automatically published to bintray.

**Comment by ctran** [comment]
Versions are available on Bintray:
> https://bintray.com/ctran/maven/tinyradius
